require("dotenv").config();
const express=require("express"),path=require("path"),crypto=require("crypto"),{Pool}=require("pg");
const app=express();
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
app.use(express.json({limit:"5mb"}));
app.use(express.static(path.join(__dirname,"public")));
const tokens=new Set();
async function init(){await pool.query(`create table if not exists consent_submissions(id bigserial primary key,cohort text not null default '미지정',name text not null,platoon text not null,birth_date text not null,agree1 boolean not null,agree2 boolean not null,agree3 boolean not null,agree4 boolean not null,agree5 boolean not null,signature_data text not null,submitted_at timestamptz not null default now())`)}
app.post("/api/consents",async(req,res)=>{try{let b=req.body,a=["agree1","agree2","agree3","agree4","agree5"].map(k=>b[k]==="on"||b[k]===true);if(!b.name||!b.platoon||!b.birthDate||!b.signature||a.some(v=>!v))return res.status(400).json({error:"필수 항목을 확인해 주세요."});await pool.query(`insert into consent_submissions(cohort,name,platoon,birth_date,agree1,agree2,agree3,agree4,agree5,signature_data) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[b.cohort||"미지정",b.name,b.platoon,b.birthDate,...a,b.signature]);res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:"서버 오류"})}});
app.post("/api/admin/login",(req,res)=>{const expected=process.env.ADMIN_PASSWORD;if(!expected)return res.status(500).json({error:"ADMIN_PASSWORD 환경변수를 설정하세요."});if(req.body.password!==expected)return res.status(401).json({error:"비밀번호가 틀렸습니다."});const token=crypto.randomBytes(24).toString("hex");tokens.add(token);res.json({token})});
function auth(req,res,next){const h=req.headers.authorization||"",t=h.startsWith("Bearer ")?h.slice(7):req.query.token;if(!t||!tokens.has(t))return res.status(401).json({error:"관리자 인증 필요"});next()}
app.get("/api/admin/consents",auth,async(req,res)=>{try{const q=`%${req.query.q||""}%`,cohort=`%${req.query.cohort||""}%`;const r=await pool.query(`select * from consent_submissions where (name ilike $1 or platoon ilike $1) and cohort ilike $2 order by submitted_at desc`,[q,cohort]);const stats={c1:0,c2:0,c3:0};for(const x of r.rows){if(String(x.platoon).startsWith("1"))stats.c1++;if(String(x.platoon).startsWith("2"))stats.c2++;if(String(x.platoon).startsWith("3"))stats.c3++}res.json({total:r.rows.length,stats,rows:r.rows})}catch(e){console.error(e);res.status(500).json({error:"서버 오류"})}});
app.delete("/api/admin/consents/:id",auth,async(req,res)=>{await pool.query("delete from consent_submissions where id=$1",[req.params.id]);res.json({ok:true})});
app.get("/api/admin/consents.csv",auth,async(req,res)=>{const r=await pool.query("select cohort,name,platoon,birth_date,agree1,agree2,agree3,agree4,agree5,submitted_at from consent_submissions order by submitted_at desc");const esc=v=>`"${String(v??"").replace(/"/g,'""')}"`;const lines=[["기수","이름","소대번호","생년월일","동의1","동의2","동의3","동의4","동의5","제출시간"].map(esc).join(",")];for(const x of r.rows)lines.push([x.cohort,x.name,x.platoon,x.birth_date,x.agree1,x.agree2,x.agree3,x.agree4,x.agree5,x.submitted_at].map(esc).join(","));res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",'attachment; filename="consents.csv"');res.send("\ufeff"+lines.join("\n"))});
app.get("/api/health",(q,s)=>s.json({ok:true}));
const PORT=process.env.PORT||3000;
init().then(()=>app.listen(PORT,()=>console.log("Server running on",PORT))).catch(e=>{console.error(e);process.exit(1)});
